"use client"
import "@/styles/globals.css"
import { Metadata } from "next"
import { cn } from "@/lib/utils"
import { SiteHeader } from "@/components/site-header"
import { ThemeProvider } from "@/components/theme-provider"
import { usePathname,useRouter } from "next/navigation" 
const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode
}
const disableNavbar = ["/login", "/register"];
export default function RootLayout({ children }: RootLayoutProps) {
  const pathname = usePathname();
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased"
          )}
        >
          
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {!disableNavbar.includes(pathname) && <SiteHeader />};
            {/* <SiteHeader/> */}
            <div className="relative flex min-h-screen flex-col">
              <div className="flex-1">{children}</div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
